FROM nginx:latest
#From the directory of the running container/image ?
WORKDIR /usr/share/nginx/html
#copy everything from the the current directory to the image, remember 
    #the current directory is linked to the directory in the container
COPY . .
